config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  
  resources :users do
    collection do
  		post :search
  	end
  end

  resources :posts do
    resources :comments do
      resources :likes
    end
    resources :likes
  end
  
  resources :friends do
    member do
      get :frequest
    end
  end
  

  root to: 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post, foreign_key: :post_id
	belongs_to :user, foreign_key: :user_id
	has_many :likes, as: :likeable, dependent: :destroy

	def is_comment_owner? current_user_id
		user_id == current_user_id
	end
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :sender, class_name: 'User', foreign_key: :sender_id
	belongs_to :receiver, class_name: 'User', foreign_key: :receiver_id

	enum status: [:new_request,:added,:rejected]
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :likeable, foreign_key: :likeable_id, polymorphic: true
	belongs_to :user, foreign_key: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true, length: {minimum: 5, maximum: 50}
	validates :data, presence: :true,length: {minimum: 10}
	belongs_to :user,foreign_key: :user_id 
	has_many :likes,as: :likeable, dependent: :destroy
	has_many :comments, dependent: :destroy, inverse_of: :post
	accepts_nested_attributes_for :comments, reject_if: :all_blank, allow_destroy: true
	
	def is_post_owner? current_user_id
		user_id == current_user_id
	end

	def existing_user_like current_user_id
		likes.find_by(user_id: current_user_id)
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :requests_send,foreign_key: :sender_id, class_name: "Friend"
  has_many :requests_received,foreign_key: :receiver_id, class_name: "Friend"
  has_many :friends, foreign_key: :receiver_id
  has_many :friendships, -> { where(friends: {status: 'added'}) }, :through => :friends, source: :sender

  has_many :comments, dependent: :destroy
  has_many :posts,dependent: :destroy
  has_many :likes, dependent: :destroy  

  def friend_requests
  	friends.where(status: :new_request)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
		users_path
  end

  def after_update_path_for(resource)
    users_path
  end

  protected
  
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name])  	
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :find_post

	def create
		@comment = @post.comments.build(comment_params)
		@comment.user_id = current_user.id
		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end 

	private

	def comment_params
		params.permit(:comment_text)
	end

	def find_post
		@post = Post.find(params[:post_id])
	end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

	def create
		@receiver = User.find(params[:format])
		@friend = Friend.create(sender_id: current_user.id,receiver_id: @receiver.id, status: :new_request)
		redirect_to user_path(current_user)
	end
	
	def index
		@friends = current_user.friendships
	end
	
	def frequest
		@requests = current_user.friend_requests
	end

	def update
		@friend = Friend.find(params[:id])
		@friend.update(status: params[:status])
		redirect_to frequest_friend_path(current_user.id)	
	end
	
	def destroy
		@friend = Friend.find_by("sender_id = ? AND receiver_id = ?",params[:id],current_user.id)
		@friend.destroy
		redirect_to friends_path
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	
	before_action :find_likeable

	def create
		@like = @likeable.likes.build(user: current_user)
		@like.save!
	end 

	def destroy
		@like = @likeable.likes.find(params[:id])
		@like.destroy
	end                    

	private

	def find_likeable
		params.each { |name,value| @likeable = $1.classify.constantize.find(value) if name =~ /(.+)_id$/}
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	before_action :find_post, only: [:show,:edit,:update,:destroy]

	def new
		@post = Post.new
	end 

	def show 
		@like = @post.existing_user_like(current_user.id)
		@comments = @post.comments
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to posts_path
		else
			render 'new'
		end
	end

	def update
		if @post.update(post_params)
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def index
		users = current_user.friendships.ids
		users<<current_user.id
		@posts = Post.includes(:user).where(user_id: users) 
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end
	
	private
	
	def post_params
		params.require(:post).permit(:title, :data, likes_attributes: [:likeable], comments_attributes:[:id, :comment_text])
	end

	def find_post
		@post = Post.find(params[:id])
	end		
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	protected
	def after_update_path_for(resource)
		home_path(resource)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except: [:index, :search]	
	def search
		@users = User.where("name like ?" ,"%#{params[:name]}%")
	end
	
	def show
		@user = User.find(params[:id])
	end		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/frequest.html.erb
<% @requests.each do |r| %>
	<% @u = User.find(r.sender_id) %>		
	<%= @u.name %>
	<%= link_to 'Accept',friend_path(r,{:status => :added}),method: :put%>
	<%= link_to 'Reject',friend_path(r,{:status => :rejected}),method: :put%><br>
<%end%>
<%= link_to 'Back', user_path(current_user) %>

app/views/friends/index.html.erb
<ul class="list-group">
	<% @friends.each do |f| %>
		<li class="list-group-item"><%= f.name %>
			<%= link_to 'Remove',friend_path(f),method: :delete%><br>
		</li>
	<%end%>
</ul>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="#">Logo</a>
  
  <!-- Links -->
  <ul class="navbar-nav">
    <li>
      <% if current_user %>
        <%= link_to "Signout", destroy_user_session_path, method: :delete, class: "nav-link" %>  
      <% else%>
        <%= link_to "Signin", new_user_session_path, class: "nav-link" %>
      <%end%>
    </li>
    <li>
      <%= link_to "Signup",  new_user_registration_path, class: "nav-link"%>      
      <!--<a class="nav-link" href="<%= new_user_session_path%>">Sign in</a>-->
    </li>
  </ul>
</nav>

app/views/layouts/_list.html.erb
<div class="row">
	<div class="col-sm-2">
			<ul class="bg-dark" >
				<li><%= link_to 'Posts', posts_path%></li>
				<li><%= link_to 'Edit Profile', edit_user_registration_path%></li>
				<li><%= link_to 'Friends', friends_path%></li>
				<li><%= link_to 'Friend Requests', frequest_friend_path(current_user)%></li>
			</ul>
		</nav>
	</div>
	<div class="col-sm-10">
		<%= form_with url: search_users_path,local: true do |form| %>
			<p>
				<%= form.text_field :name%>
				<%= form.submit 'Search'%>
			</p>
		<%end%>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%if current_user %>
      <%= render 'layouts/list'%>
      <%= render 'layouts/search'%>
    <%end%> 
    <%= yield %>
  </body>
</html>

app/views/likes/create.js.erb
$("#like-<%= @likeable.id%>").attr("href", '<%=post_like_path(@likeable,@like)%>').attr("data-method", 'delete').text("Unlike")
$("#like-count").html("<%= pluralize(@likeable.likes.size, 'like')%>")

app/views/likes/destroy.js.erb
$("#like-<%= @likeable.id%>").attr("href","<%= post_likes_path(@likeable)%>").attr("data-method","post").text("Like")
$("#like-count").html("<%= pluralize(@likeable.likes.size, 'like')%>")

app/views/posts/_form.html.erb
<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-10">
		<% if @post.errors.any? %>
	    <div id="error_explanation">
  	    <h2>
 	       <%= pluralize(@post.errors.count, "error") %> prohibited
	        this post from being saved:
	      </h2>
	      <ul>
  	      <% @post.errors.full_messages.each do |msg| %>
    	      <li><%= msg %></li>
    	    <% end %>
    	  </ul>
    	</div>
 		<% end %>
		<%= form_with model: @post, local: true do |form| %>
			<p>
				<%= form.label :title %><br>
				<%= form.text_field :title%><br>
			</p>
			<p>
				<%= form.label :data%><br>
				<%= form.text_area :data%>
			</p>
			<p>
				<%= form.submit%>
			</p>
		<%end%>
	</div>
</div>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render 'form' %>
<%= link_to 'Back', posts_path(current_user) %>

app/views/posts/index.html.erb
<%= link_to 'Add New Post', new_post_path %>
<table class="table-bordered">
	<tr>
		<th>User</th>
		<th>Title</th>
		<th>Text</th>
		<th colspan="2"></th>
	</tr>
	<% @posts.each do |post|%>
		<tr>
			<td><%= post.user.name %></td>
			<td><%= post.title%></td>
			<td><%= post.data %></td>
			<td><%= link_to 'Show',post_path(post)%></td>
			<% if post.is_post_owner? current_user.id %>
				<td><%= link_to 'Edit', edit_post_path(post)%></td> 
				<td><%= link_to 'Delete', post_path(post),method: :delete%></td>
			<%end%>
		</tr>
	<% end %>
</table>
<%= link_to 'Back', user_path(current_user) %>

app/views/posts/new.html.erb
<h3>Create New Post</h3>
<%= render 'form'%>

app/views/posts/show.html.erb
<div>
	<p>
		<strong><%= @post.user.name%></strong>
	</p>
	
	<p>
		<strong>Title:</strong>
		<%= @post.title%>
	</p>
	
	<p>
		<strong>Text:</strong>
		<%= @post.data%>
	</p>
	
	<p id = "like-count"><%= pluralize(@post.likes.size, 'like')%></p>
	
	<p>
		<% if @like %>
			<%= link_to 'Unlike', post_like_path(@post,@like), method: :delete, remote: true, id: "like-#{@post.id}"%>
		<%else%>
			<%= link_to 'Like', post_likes_path(@post), method: :post, remote: true, id: "like-#{@post.id}"%>
		<%end%>
	</p>
</div>

<div id = "comments-list">
	<strong>Comments List:</strong>
	<% @comments.each do |comment| %>
		<p>
			<strong>Comment:</strong>
			<%= comment.comment_text %>
			<% if comment.is_comment_owner? current_user.id %>
				<%= link_to 'Delete', post_comment_path(@post,comment),method: :delete%></td>
			<%end%>
		</p>
	<%end%>
</div>

<div id = "new-comment-form">
	<strong>Add a Comment</strong>
	<%= form_with(model: @comment, url: post_comments_path(@post), local: true) do |form| %>
		<p>
			<%= form.text_field :comment_text %>
		</p>
		<p>
			<%= form.submit %>
		</p>
	<%end%>
</div>

<%= link_to 'Back', posts_path(current_user) %>																																																																																																																

app/views/users/index.html.erb
<h2 class = "text-center">Home</h2>
<!--<div class="btn">
	<%= link_to 'Signup',  new_user_registration_path%><br>
	<%= link_to "Signin", new_user_session_path %>
</div>-->

app/views/users/search.html.erb
<% @users.each do |user|%>
	<%= user.name %>
	<%= link_to "Add", friends_path(user), method: :post%><br>
<% end%>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>